sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
# - npm run coveralls
after_success: "npm run postcoverage && <coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
after_success: npm run coveralls
